// Server-level instructions surfaced to the MCP client (Claude Desktop, Cursor, etc.)
// alongside the tool list. These guide the agent's behavior across all calls.
//
// Edit freely; bullet lists with a top-line topic name make appending new hints easy.

export const SERVER_INSTRUCTIONS = [
  "**Two paths to a GQLDB instance:**",
  "1. **Cloud-managed instances** (set `ULTIPA_CLOUD_API_KEY` in MCP's env). Ultipa Cloud is a DBaaS platfrom that fully manages GQLDB instances. Instances discoverable via `list_instances`. State-change tools (create, pause, resume, delete, etc.) operate on these. To connect to one of these instances, pass its `_id` as the `id` arg and get credientials via `get_instance_credentials`. Run queries on the instance with data-plane tools (`run_gql_query`, `list_graphs`, `describe_schema`, etc.).",
  "2. **Directly-configured instance** (set `ULTIPA_HOST` + `ULTIPA_USERNAME` + `ULTIPA_PASSWORD` + optional `ULTIPA_GRAPH` in MCP's env). To connect to it, call a data-plane tool WITHOUT an `id` arg, the MCP routes the call to the env-configured instance.",
  "",
  "`list_instances` only sees Cloud instances. A Direct instance (configured via `ULTIPA_HOST` in MCP's env) does NOT appear there but is reachable via data-plane tools without an `id` arg. If the user asks about a self-managed / local instance, do not conclude 'not visible' from `list_instances` — call `test_connection` (omit `id`). If it returns `ok: true`, a Direct instance is configured and reachable; if it errors with 'Direct instance is not configured', then only Ultipa Cloud is set up in this MCP.",
  "",
  "For Cloud instances, the `adminPassword` is NOT returned by `list_instances` or `get_instance`. To fetch it, call `get_instance_credentials` (requires `ULTIPA_CLOUD_API_KEY` to have the `instances:credentials` permission). After a successful `create_instance`, immediately call `get_instance_credentials` and surface the password to the user — that's how they get the initial password.",
  "",
  "If `get_instance_credentials` fails on permissions, the recovery options are: (1) copy the password from https://dbaas.ultipa.com → instance detail page, (2) regenerate the API key with the `instances:credentials` permission enabled and reconnect, or (3) only when the user explicitly asks to rotate the password, call `reset_admin_password`.",
  "",
  "**Use `lookup_docs` aggressively.** Training-time knowledge of Ultipa GQLDB or GQL is patchy and often wrong on edges. For ANY Ultipa or GQL specific question — schema design, GQL syntax, function signatures, ontology features, algorithm catalog — call `lookup_docs` FIRST and use the returned markdown as ground truth instead of guessing. The tool's description and empty-call response list the curated entry points; call `lookup_docs({ topic: \"?\" })` for the full live index.",
  "",
  "The query language is **GQL** (the ISO/IEC 39075 standard Graph Query Language). It is NOT UQL, Cypher, or GraphQL. To answer data questions against a graph (e.g. 'what's the max age of users', 'count books by author X'):",
  "1. An instance can host multiple graphs (check via `list_graphs`). One graph is marked as 'current' and queries run against it. Before running a query, ensure you know which graph the user is now working with.",
  "2. If you don't already know the graph schema/structure, call `describe_schema`. Discover node/edge label names and property names before composing GQL.",
  "3. Compose the GQL query. For any syntax you're not certain about, follow the `lookup_docs` rule above.",
  "4. Run GQL query via `run_gql_query` and report the result in natural language.",
  "5. If the first run returns zero rows or errors, the schema is probably mis-guessed. Re-check `describe_schema` and retry, don't keep guessing.",
  "",
  "**For complex analytical questions** ('find influential users', 'detect communities', 'graph embedding', etc.), check whether a built-in graph algorithm or stored procedure fits BEFORE composing custom GQL. They are dramatically faster than hand-computed GQL on large graphs and can do things normal GQL query cannot do. Discovery:",
  "- **Built-in algorithms** (run via `run_algo`): `lookup_docs('graph-algorithms/pages/introduction')` for the also catalog by category, then `lookup_docs('graph-algorithms/pages/<category>/<algorithm>')` for one algorithm details (e.g. `centrality/pagerank`, `community-detection/louvain`). If needs to further process algo results, you may combine it with other GQL statements and run via `run_gql_query`.",
  "- **Stored procedures**: to call a procedure, use `run_gql_query` with `CALL <procedureName>(...)` (list available with `SHOW PROCEDURES`; see `lookup_docs('stored-procedures/pages/calling-procedures')`). To **create** a procedure, use `write_procedure` — the procedure body has its own grammar (NOT GQL), so always `lookup_docs('stored-procedures/pages/procedure-body-language')` first.",
  "",
  "If user wants to add / load / import data into a graph, **decide first by where the data lives**:",
  "- **User attached / uploaded / pasted a file (csv, json, jsonl, graphml, etc.) or pasted row-shaped text** → use **`import_data`**. Parse the source yourself into canonical `nodes` / `edges` arrays and pass them in one call. DO NOT hand-compose `INSERT` statements row-by-row; that is exactly what `import_data` is for. Good for up to ~tens of thousands of rows.",
  "- **User wrote out a small literal record in-conversation** (e.g. 'add a User node with name=Alice') or wants a non-INSERT statement (`UPSERT` / `MERGE` / `INSERT OVERWRITE` / `FOREACH`) → use **`write_data`** with hand-composed GQL.",
  "- **CSV file already on the GQLDB server's filesystem** (not the user's machine) → use **`write_data`** with a `LOAD CSV` statement (single server-side round trip).",
  "- **Very large imports** (millions of rows, live SQL databases, other graph platforms, big-data systems) → suggest **Ultipa Manager → Data Integration** (UI wizard, built into Manager — Cloud instances open via `managerUrl`) or **Ultipa Transporter** (batch ETL CLI, https://www.ultipa.com/docs/tools/transporter).",
  "- **Before calling `import_data`** (or composing a `LOAD CSV` with non-trivial `MAPPING` via `write_data`), preview your plan to the user in a short block: node / edge labels, which source column maps to `_id`, which columns map to `_from` / `_to` for edges, which columns become which properties, the `mode` (`normal` / `overwrite` / `upsert`), and approximate row counts. Wait for 'go' or corrections. Skip the preview only when the user pre-specified every mapping explicitly in this turn. Silent inferences on bulk writes are hard to undo.",
  "",
  "If queries on a large graph are slow, suggest performance options to the user before just retrying:",
  "- **Index** accelerate property filtering in predicates, created via `CREATE INDEX` (run through `run_gql_query`, syntax in `lookup_docs('gql/pages/query-acceleration/index')`). For text search use `CREATE FULLTEXT INDEX` (`lookup_docs('gql/pages/query-acceleration/fulltext-index')`). **Do NOT create indexes without explicit user confirmation** — each index costs storage and slows writes, so wrong indexes are net-negative.",
  "- **Enable Computing Engine** for analytical / heavy workloads (graph algorithms like PageRank / community detection, multi-hop traversals, heavy aggregations). It's an instance-level add-on. Details in `lookup_docs('computing-engine/pages/introduction')`.",
  "",
  "If user asks how to connect to an instance, refer the options below:",
  "1. **Ultipa Manager.** If it's a Cloud instance, open the instance's `managerUrl` in a browser. Easiest first-touch — gives a query editor, schema view, metrics, etc.",
  "2. **Drivers.** Include Python, Java, Go, and . See https://www.ultipa.com/docs/drivers.",
  "3. **Ultipa CLI.** A command-line tool for running queries. See https://www.ultipa.com/docs/tools/cli.",
  "",
].join("\n");
